### ISSUE TITLE
Doesn’t work with `csstools.postcss`

### ISSUE THREAD

**Issue by ai** [walnuts1018/oklch-vscode#2]
Hi! oklch.com and PostCSS author here. Thanks for the amazing tool.

It works great for `css` syntax, but I use [`csstools.postcss`](https://marketplace.visualstudio.com/items/?itemName=csstools.postcss) to support some PostCSS syntax extensions and `oklch()` doesn’t work there.

[My config](https://github.com/ai/environment/blob/main/vscode.json):

```json
  "files.associations": {
    ".stylelintrc": "json",
    "*.bu": "yaml",
    "*.css": "postcss",
    "*.desktop": "ini",
    "*.ign": "json",
    "*.service": "ini",
    "*.timer": "ini",
    "**/test/*.errors.ts": "rust",
    "errors.ts": "rust",
    "errors.tsx": "rust"
  },
"oklch-vscode.languages": [
    ".css",
    "css",
    "postcss",
  ],
```

Result:

![Image](https://github.com/user-attachments/assets/728cd3f5-4858-4064-8070-ae6424c4d2cf)

Expected (`with `".css": "css"`):

![Image](https://github.com/user-attachments/assets/10ac103c-0f1f-47bd-91b4-13d258a70171)

**Comment by walnuts1018** [comment]
Thank you for reporting this issue!

I'm a big fan of oklch.com and find it incredibly useful in my daily work.

Regarding the problem you've reported, I've conducted some tests in the following environment, but unfortunately, I haven't been able to reproduce the issue on my end:

- VSCode: 1.99.1
- settings.json: https://github.com/ai/environment/blob/main/vscode.json
- Installed Extensions: `csstools.postcss@1.0.9`, `walnuts1018.oklch-vscode@0.1.0`
- CSS Code:
```css
:root {
  --focus-color: var(--accent-color);
  
  @media (prefers-color-scheme: light) {
    --text-color: oklch(0.15 0 0);
    --background-color: oklch(0.95 0 70);
    
    &.is-comfort-mode {
      --land-color: oklch(0.95 0.02 70)
    }
  }
}
```

![Image](https://github.com/user-attachments/assets/8f424cdd-79ab-4cd2-b5c8-5284db00b37d)

I suspect that another extension might be interfering, but I can't say for sure at this point.

I will investigate this further on my side.

In the meantime, I'd like to make a change to include "postcss" in the default `"oklch-vscode.languages"` setting.
